/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DateTimePicker: typeof import('./src/packages/dateTimePicker/dateTimePicker.vue')['default']
    EmptyState: typeof import('./src/packages/emptyState/emptyState.vue')['default']
    EventRecord: typeof import('./src/packages/eventRecord/eventRecord.vue')['default']
    InspectTable: typeof import('./src/packages/inspectTable/inspectTable.vue')['default']
    Layout: typeof import('./src/packages/layout/layout.vue')['default']
    Pagination: typeof import('./src/packages/pagination/pagination.vue')['default']
    Password: typeof import('./src/packages/password/password.vue')['default']
    Process: typeof import('./src/packages/process/process.vue')['default']
    RollNumber: typeof import('./src/packages/rollNumber/rollNumber.vue')['default']
    SearchBox: typeof import('./src/packages/searchBox/searchBox.vue')['default']
    SearchItem: typeof import('./src/packages/searchItem/searchItem.vue')['default']
    SpringBox: typeof import('./src/packages/springBox/springBox.vue')['default']
    Status: typeof import('./src/packages/status/status.vue')['default']
    TableWidgets: typeof import('./src/packages/tableWidgets/tableWidgets.vue')['default']
    Tooltip: typeof import('./src/packages/tooltip/tooltip.vue')['default']
    Transfer: typeof import('./src/packages/transfer/transfer.vue')['default']
    TransferPanel: typeof import('./src/packages/transfer/transferPanel.vue')['default']
    TreeSelect: typeof import('./src/packages/treeSelect/treeSelect.vue')['default']
    Upload: typeof import('./src/packages/upload/upload.vue')['default']
  }
}
