/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ZrxDateTimePicker: typeof import('./src/packages/dateTimePicker/dateTimePicker.vue')['default']
    ZrxEmptyState: typeof import('./src/packages/emptyState/emptyState.vue')['default']
    ZrxEventRecord: typeof import('./src/packages/eventRecord/eventRecord.vue')['default']
    ZrxInspectTable: typeof import('./src/packages/inspectTable/inspectTable.vue')['default']
    ZrxLayout: typeof import('./src/packages/layout/layout.vue')['default']
    ZrxPagination: typeof import('./src/packages/pagination/pagination.vue')['default']
    ZrxPassword: typeof import('./src/packages/password/password.vue')['default']
    ZrxProcess: typeof import('./src/packages/process/process.vue')['default']
    ZrxRollNumber: typeof import('./src/packages/rollNumber/rollNumber.vue')['default']
    ZrxSearchBox: typeof import('./src/packages/searchBox/searchBox.vue')['default']
    ZrxSearchItem: typeof import('./src/packages/searchItem/searchItem.vue')['default']
    ZrxSpringBox: typeof import('./src/packages/springBox/springBox.vue')['default']
    ZrxStatus: typeof import('./src/packages/status/status.vue')['default']
    ZrxTableWidgets: typeof import('./src/packages/tableWidgets/tableWidgets.vue')['default']
    ZrxTooltip: typeof import('./src/packages/tooltip/tooltip.vue')['default']
    ZrxTransfer: typeof import('./src/packages/transfer/transfer.vue')['default']
    ZrxTransferPanel: typeof import('./src/packages/transfer/transferPanel.vue')['default']
    ZrxTreeSelect: typeof import('./src/packages/treeSelect/treeSelect.vue')['default']
    ZrxUpload: typeof import('./src/packages/upload/upload.vue')['default']
  }
}
